In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from fractions import Fraction

import plotly.express as px

pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None

%matplotlib inline

In [2]:
#this is a custom function to open each dataset
def open_fuel_year(fuel_year):
    
    df = pd.read_csv('./data_'+str(fuel_year)+'_v2.csv', low_memory=False)

    df['record_year'] = pd.Series(dtype='str')
    new_cols_order = ['record_year'] + df.columns[0:18].to_list()
    
    df = df[new_cols_order]
    for year in years:
        if year == fuel_year:
            df['record_year'] = int(fuel_year)
            print(new_cols_order)    
        
    return df

In [3]:
clean_df = pd.DataFrame()

years = [2008,2018]

#join the datasets
for fuel_year in years:
    clean_df = pd.concat([clean_df, open_fuel_year(fuel_year)])
    
    print(len(clean_df))
clean_df.reset_index(drop=True, inplace=True)

['record_year', 'record_year', 'model', 'displ', 'cyl', 'trans', 'drive', 'fuel', 'cert_region', 'veh_class', 'air_pollution_score', 'city_mpg', 'hwy_mpg', 'cmb_mpg', 'greenhouse_gas_score', 'smartway']
2142
['record_year', 'record_year', 'model', 'displ', 'cyl', 'trans', 'drive', 'fuel', 'cert_region', 'veh_class', 'air_pollution_score', 'city_mpg', 'hwy_mpg', 'cmb_mpg', 'greenhouse_gas_score', 'smartway']
3746

In [4]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3746 entries, 0 to 3745
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   record_year           3746 non-null   int64
 1   record_year           3746 non-null   int64
 2   model                 3746 non-null   object
 3   displ                 3746 non-null   float64
 4   cyl                   3746 non-null   object
 5   trans                 3746 non-null   object
 6   drive                 3746 non-null   object
 7   fuel                  3746 non-null   object
 8   cert_region           3746 non-null   object
 9   veh_class             3746 non-null   object
 10  air_pollution_score   3746 non-null   object
 11  city_mpg              3746 non-null   object
 12  hwy_mpg               3746 non-null   object
 13  cmb_mpg               3746 non-null   object
 14  greenhouse_gas_score  3746 non-null   object
 15  smartway              3746 non-null   object
dtypes: float64(1), int64(2), object(13)
memory usage: 468.4+ KB

In [5]:
clean_df

,record_year,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,2008,2008,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no
1,2008,2008,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,15,20,17,4,no
2,2008,2008,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,17,22,19,5,no
3,2008,2008,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,17,22,19,5,no
4,2008,2008,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,midsize car,7,16,24,19,5,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3741,2018,2018,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,FA,standard SUV,5,22,28,24,5,No
3742,2018,2018,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,CA,standard SUV,5,20,27,23,5,No
3743,2018,2018,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,FA,standard SUV,5,20,27,23,5,No
3744,2018,2018,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,CA,standard SUV,7,26/63,30/61,27/62,10,Elite
3745,2018,2018,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,FA,standard SUV,7,26/63,30/61,27/62,10,Elite

In [6]:
clean_df = clean_df.T.drop_duplicates()

In [7]:
clean_df = clean_df.T
clean_df

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,2008,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no
1,2008,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,15,20,17,4,no
2,2008,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,17,22,19,5,no
3,2008,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,17,22,19,5,no
4,2008,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,midsize car,7,16,24,19,5,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3741,2018,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,FA,standard SUV,5,22,28,24,5,No
3742,2018,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,CA,standard SUV,5,20,27,23,5,No
3743,2018,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,FA,standard SUV,5,20,27,23,5,No
3744,2018,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,CA,standard SUV,7,26/63,30/61,27/62,10,Elite
3745,2018,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,FA,standard SUV,7,26/63,30/61,27/62,10,Elite

In [8]:
type(clean_df.greenhouse_gas_score[99])

str

In [9]:
clean_df.greenhouse_gas_score.value_counts()

6      568
5      455
5      369
4      326
7      316
3      308
4      279
6      219
3      160
2      148
8      131
7      126
2       70
0       50
8       40
1       33
10      28
6/4     24
1       22
9       19
4/3     15
4/2     11
9       10
10       4
8/6      4
6/5      3
5/3      3
7/6      3
6/3      1
7/5      1
Name: greenhouse_gas_score, dtype: int64

In [10]:
# extract all number values in the cylinder column
clean_df['cyl'] = clean_df['cyl'].astype('str').str.extractall('(\d+)').unstack().fillna('').sum(axis=1).astype(int)

In [11]:
v08 = clean_df.query('record_year == 2008')
v18 = clean_df.query('record_year == 2018')

In [12]:
# First, let's get all the hybrids in 2008
hb_08 = v08[v08['fuel'].str.contains('/')]
hb_08

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
306,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,2WD,ethanol/gas,FC,SUV,7/7,11/14,15/20,12/16,6/4,no
307,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,4WD,ethanol/gas,FC,SUV,7/7,11/14,14/19,12/16,6/4,no
311,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,2WD,ethanol/gas,FC,SUV,6/6,11/14,15/20,12/16,6/4,no
312,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,4WD,ethanol/gas,FC,SUV,6/6,11/14,14/19,12/16,6/4,no
367,2008,CHEVROLET Express 1500,5.3,8,Auto-L4,4WD,ethanol/gas,FC,van,6/6,9/12,12/16,10/14,4/2,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1489,2008,MITSUBISHI Raider,4.7,8,Auto-L5,4WD,ethanol/gas,FA,pickup,3/3,9/14,12/19,10/15,4/3,no
1519,2008,NISSAN Armada,5.6,8,Auto-L5,2WD,ethanol/gas,FA,SUV,6/6,9/12,13/18,10/14,4/2,no
1520,2008,NISSAN Armada,5.6,8,Auto-L5,4WD,ethanol/gas,FA,SUV,6/6,9/12,13/17,10/14,4/2,no
1563,2008,NISSAN Titan,5.6,8,Auto-L5,2WD,ethanol/gas,FA,pickup,6/6,9/12,13/17,10/14,4/2,no
1564,2008,NISSAN Titan,5.6,8,Auto-L5,4WD,ethanol/gas,FA,pickup,6/6,9/12,12/17,10/14,4/2,no

In [13]:
# hybrids in 2018
hb_18 =v18[v18['fuel'].str.contains('/')]
hb_18

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
2249,2018,BMW 330e,2.0,40,SemiAuto-8,2WD,Gasoline/Electricity,CA,small car,3,28/66,34/78,30/71,10,Yes
2250,2018,BMW 330e,2.0,40,SemiAuto-8,2WD,Gasoline/Electricity,FA,small car,3,28/66,34/78,30/71,10,Yes
2301,2018,BMW 530e,2.0,40,SemiAuto-8,2WD,Gasoline/Electricity,CA,small car,7,27/70,31/75,29/72,10,Elite
2302,2018,BMW 530e,2.0,40,SemiAuto-8,2WD,Gasoline/Electricity,FA,small car,7,27/70,31/75,29/72,10,Elite
2303,2018,BMW 530e,2.0,40,SemiAuto-8,4WD,Gasoline/Electricity,CA,small car,7,27/66,31/68,28/67,10,Elite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3713,2018,VOLVO S90,2.0,40,SemiAuto-8,4WD,Gasoline/Electricity,FA,midsize car,7,26/70,33/72,29/71,10,Elite
3736,2018,VOLVO XC 60,2.0,40,SemiAuto-8,4WD,Gasoline/Electricity,CA,small SUV,7,26/60,28/58,26/59,10,Elite
3737,2018,VOLVO XC 60,2.0,40,SemiAuto-8,4WD,Gasoline/Electricity,FA,small SUV,7,26/60,28/58,26/59,10,Elite
3744,2018,VOLVO XC 90,2.0,40,SemiAuto-8,4WD,Gasoline/Electricity,CA,standard SUV,7,26/63,30/61,27/62,10,Elite
3745,2018,VOLVO XC 90,2.0,40,SemiAuto-8,4WD,Gasoline/Electricity,FA,standard SUV,7,26/63,30/61,27/62,10,Elite

In [14]:
df1 = hb_08.copy()  # data on first fuel type of each hybrid vehicle
df2 = hb_08.copy()  # data on second fuel type of each hybrid vehicle
df3 = hb_18.copy()
df4 = hb_18.copy()

In [15]:
df1

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
306,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,2WD,ethanol/gas,FC,SUV,7/7,11/14,15/20,12/16,6/4,no
307,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,4WD,ethanol/gas,FC,SUV,7/7,11/14,14/19,12/16,6/4,no
311,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,2WD,ethanol/gas,FC,SUV,6/6,11/14,15/20,12/16,6/4,no
312,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,4WD,ethanol/gas,FC,SUV,6/6,11/14,14/19,12/16,6/4,no
367,2008,CHEVROLET Express 1500,5.3,8,Auto-L4,4WD,ethanol/gas,FC,van,6/6,9/12,12/16,10/14,4/2,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1489,2008,MITSUBISHI Raider,4.7,8,Auto-L5,4WD,ethanol/gas,FA,pickup,3/3,9/14,12/19,10/15,4/3,no
1519,2008,NISSAN Armada,5.6,8,Auto-L5,2WD,ethanol/gas,FA,SUV,6/6,9/12,13/18,10/14,4/2,no
1520,2008,NISSAN Armada,5.6,8,Auto-L5,4WD,ethanol/gas,FA,SUV,6/6,9/12,13/17,10/14,4/2,no
1563,2008,NISSAN Titan,5.6,8,Auto-L5,2WD,ethanol/gas,FA,pickup,6/6,9/12,13/17,10/14,4/2,no
1564,2008,NISSAN Titan,5.6,8,Auto-L5,4WD,ethanol/gas,FA,pickup,6/6,9/12,12/17,10/14,4/2,no

In [16]:
# columns to split by "/"
split_columns = ['fuel', 'air_pollution_score', 'city_mpg', 'hwy_mpg', 'cmb_mpg', 'greenhouse_gas_score']
split_columns2 = ['fuel', 'city_mpg', 'hwy_mpg', 'cmb_mpg']

# apply split function to each column of each 08 dataframe copy
for c in split_columns:
    df1[c] = df1[c].apply(lambda x: x.split("/")[0])
    df2[c] = df2[c].apply(lambda x: x.split("/")[1])
    
# apply split function to each column of each 18 dataframe copy
for c in split_columns2:
    df3[c] = df3[c].apply(lambda x: x.split("/")[0])
    df4[c] = df4[c].apply(lambda x: x.split("/")[1])

In [23]:
df1.query('fuel == "ethanol"')

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
306,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,2WD,ethanol,FC,SUV,7,11,15,12,6,no
307,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,4WD,ethanol,FC,SUV,7,11,14,12,6,no
311,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,2WD,ethanol,FC,SUV,6,11,15,12,6,no
312,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,4WD,ethanol,FC,SUV,6,11,14,12,6,no
367,2008,CHEVROLET Express 1500,5.3,8,Auto-L4,4WD,ethanol,FC,van,6,9,12,10,4,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1489,2008,MITSUBISHI Raider,4.7,8,Auto-L5,4WD,ethanol,FA,pickup,3,9,12,10,4,no
1519,2008,NISSAN Armada,5.6,8,Auto-L5,2WD,ethanol,FA,SUV,6,9,13,10,4,no
1520,2008,NISSAN Armada,5.6,8,Auto-L5,4WD,ethanol,FA,SUV,6,9,13,10,4,no
1563,2008,NISSAN Titan,5.6,8,Auto-L5,2WD,ethanol,FA,pickup,6,9,13,10,4,no
1564,2008,NISSAN Titan,5.6,8,Auto-L5,4WD,ethanol,FA,pickup,6,9,12,10,4,no

In [24]:
df4

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
2249,2018,BMW 330e,2.0,40,SemiAuto-8,2WD,Electricity,CA,small car,3,66,78,71,10,Yes
2250,2018,BMW 330e,2.0,40,SemiAuto-8,2WD,Electricity,FA,small car,3,66,78,71,10,Yes
2301,2018,BMW 530e,2.0,40,SemiAuto-8,2WD,Electricity,CA,small car,7,70,75,72,10,Elite
2302,2018,BMW 530e,2.0,40,SemiAuto-8,2WD,Electricity,FA,small car,7,70,75,72,10,Elite
2303,2018,BMW 530e,2.0,40,SemiAuto-8,4WD,Electricity,CA,small car,7,66,68,67,10,Elite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3713,2018,VOLVO S90,2.0,40,SemiAuto-8,4WD,Electricity,FA,midsize car,7,70,72,71,10,Elite
3736,2018,VOLVO XC 60,2.0,40,SemiAuto-8,4WD,Electricity,CA,small SUV,7,60,58,59,10,Elite
3737,2018,VOLVO XC 60,2.0,40,SemiAuto-8,4WD,Electricity,FA,small SUV,7,60,58,59,10,Elite
3744,2018,VOLVO XC 90,2.0,40,SemiAuto-8,4WD,Electricity,CA,standard SUV,7,63,61,62,10,Elite
3745,2018,VOLVO XC 90,2.0,40,SemiAuto-8,4WD,Electricity,FA,standard SUV,7,63,61,62,10,Elite

In [25]:
# combine dataframes to add to the original dataframes
new_rows = pd.concat([df1,df2])
new_rows2 = pd.concat([df3,df4])

# now we have separate rows for each fuel type of each vehicle!
new_rows

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
306,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,2WD,ethanol,FC,SUV,7,11,15,12,6,no
307,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,4WD,ethanol,FC,SUV,7,11,14,12,6,no
311,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,2WD,ethanol,FC,SUV,6,11,15,12,6,no
312,2008,CHEVROLET Avalanche 1500,5.3,8,Auto-L4,4WD,ethanol,FC,SUV,6,11,14,12,6,no
367,2008,CHEVROLET Express 1500,5.3,8,Auto-L4,4WD,ethanol,FC,van,6,9,12,10,4,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1489,2008,MITSUBISHI Raider,4.7,8,Auto-L5,4WD,gas,FA,pickup,3,14,19,15,3,no
1519,2008,NISSAN Armada,5.6,8,Auto-L5,2WD,gas,FA,SUV,6,12,18,14,2,no
1520,2008,NISSAN Armada,5.6,8,Auto-L5,4WD,gas,FA,SUV,6,12,17,14,2,no
1563,2008,NISSAN Titan,5.6,8,Auto-L5,2WD,gas,FA,pickup,6,12,17,14,2,no
1564,2008,NISSAN Titan,5.6,8,Auto-L5,4WD,gas,FA,pickup,6,12,17,14,2,no

In [26]:
# drop the original hybrid rows
v08.drop(hb_08.index, inplace=True)
v18.drop(hb_18.index, inplace=True)

# add in our newly separated rows
v08 = pd.concat([v08, new_rows], ignore_index=True)
v18 = pd.concat([v18, new_rows2], ignore_index=True)

In [27]:
v08

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,2008,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no
1,2008,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,FA,SUV,6,15,20,17,4,no
2,2008,ACURA RDX,2.3,4,Auto-S5,4WD,Gasoline,CA,SUV,7,17,22,19,5,no
3,2008,ACURA RDX,2.3,4,Auto-S5,4WD,Gasoline,FA,SUV,6,17,22,19,5,no
4,2008,ACURA RL,3.5,6,Auto-S5,4WD,Gasoline,CA,midsize car,7,16,24,19,5,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202,2008,MITSUBISHI Raider,4.7,8,Auto-L5,4WD,gas,FA,pickup,3,14,19,15,3,no
2203,2008,NISSAN Armada,5.6,8,Auto-L5,2WD,gas,FA,SUV,6,12,18,14,2,no
2204,2008,NISSAN Armada,5.6,8,Auto-L5,4WD,gas,FA,SUV,6,12,17,14,2,no
2205,2008,NISSAN Titan,5.6,8,Auto-L5,2WD,gas,FA,pickup,6,12,17,14,2,no
2206,2008,NISSAN Titan,5.6,8,Auto-L5,4WD,gas,FA,pickup,6,12,17,14,2,no

In [28]:
# check that all the original hybrid rows with "/"s are gone
v08[v08['fuel'].str.contains('/')]

Empty DataFrame
Columns: [record_year, model, displ, cyl, trans, drive, fuel, cert_region, veh_class, air_pollution_score, city_mpg, hwy_mpg, cmb_mpg, greenhouse_gas_score, smartway]
Index: []

In [29]:
v18[v18.fuel.str.contains('/')]

Empty DataFrame
Columns: [record_year, model, displ, cyl, trans, drive, fuel, cert_region, veh_class, air_pollution_score, city_mpg, hwy_mpg, cmb_mpg, greenhouse_gas_score, smartway]
Index: []

In [30]:
v08.shape

(2207, 15)

In [31]:
v18.shape

(1683, 15)

In [32]:


v08.air_pollution_score = v08.air_pollution_score.astype('float')
v18.air_pollution_score = v18.air_pollution_score.astype('float')

In [33]:
v18

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,2018,ACURA RDX,3.5,60,SemiAuto-6,2WD,Gasoline,FA,small SUV,3.0,20,28,23,5,No
1,2018,ACURA RDX,3.5,60,SemiAuto-6,2WD,Gasoline,CA,small SUV,3.0,20,28,23,5,No
2,2018,ACURA RDX,3.5,60,SemiAuto-6,4WD,Gasoline,FA,small SUV,3.0,19,27,22,4,No
3,2018,ACURA RDX,3.5,60,SemiAuto-6,4WD,Gasoline,CA,small SUV,3.0,19,27,22,4,No
4,2018,ACURA TLX,2.4,40,AMS-8,2WD,Gasoline,CA,small car,3.0,23,33,27,6,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678,2018,VOLVO S90,2.0,40,SemiAuto-8,4WD,Electricity,FA,midsize car,7.0,70,72,71,10,Elite
1679,2018,VOLVO XC 60,2.0,40,SemiAuto-8,4WD,Electricity,CA,small SUV,7.0,60,58,59,10,Elite
1680,2018,VOLVO XC 60,2.0,40,SemiAuto-8,4WD,Electricity,FA,small SUV,7.0,60,58,59,10,Elite
1681,2018,VOLVO XC 90,2.0,40,SemiAuto-8,4WD,Electricity,CA,standard SUV,7.0,63,61,62,10,Elite
1682,2018,VOLVO XC 90,2.0,40,SemiAuto-8,4WD,Electricity,FA,standard SUV,7.0,63,61,62,10,Elite

In [34]:
v08

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,2008,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,CA,SUV,7.0,15,20,17,4,no
1,2008,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,FA,SUV,6.0,15,20,17,4,no
2,2008,ACURA RDX,2.3,4,Auto-S5,4WD,Gasoline,CA,SUV,7.0,17,22,19,5,no
3,2008,ACURA RDX,2.3,4,Auto-S5,4WD,Gasoline,FA,SUV,6.0,17,22,19,5,no
4,2008,ACURA RL,3.5,6,Auto-S5,4WD,Gasoline,CA,midsize car,7.0,16,24,19,5,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2202,2008,MITSUBISHI Raider,4.7,8,Auto-L5,4WD,gas,FA,pickup,3.0,14,19,15,3,no
2203,2008,NISSAN Armada,5.6,8,Auto-L5,2WD,gas,FA,SUV,6.0,12,18,14,2,no
2204,2008,NISSAN Armada,5.6,8,Auto-L5,4WD,gas,FA,SUV,6.0,12,17,14,2,no
2205,2008,NISSAN Titan,5.6,8,Auto-L5,2WD,gas,FA,pickup,6.0,12,17,14,2,no
2206,2008,NISSAN Titan,5.6,8,Auto-L5,4WD,gas,FA,pickup,6.0,12,17,14,2,no

In [35]:
clean_df = pd.concat([v08, v18])

In [36]:
clean_df.air_pollution_score.dtypes

dtype('float64')

In [37]:
# convert mpg columns to floats
mpg_columns = ['city_mpg', 'hwy_mpg', 'cmb_mpg']
for c in mpg_columns:
    v18[c] = v18[c].astype('float')
    v08[c] = v08[c].astype('float')

In [38]:
# convert mpg columns to floats
int_columns = ['record_year', 'greenhouse_gas_score']
for c in int_columns:
    v18[c] = v18[c].astype('int')
    v08[c] = v08[c].astype('int')

In [39]:
v08.dtypes

record_year               int32
model                    object
displ                    object
cyl                       int32
trans                    object
drive                    object
fuel                     object
cert_region              object
veh_class                object
air_pollution_score     float64
city_mpg                float64
hwy_mpg                 float64
cmb_mpg                 float64
greenhouse_gas_score      int32
smartway                 object
dtype: object

In [40]:
v08.dtypes

record_year               int32
model                    object
displ                    object
cyl                       int32
trans                    object
drive                    object
fuel                     object
cert_region              object
veh_class                object
air_pollution_score     float64
city_mpg                float64
hwy_mpg                 float64
cmb_mpg                 float64
greenhouse_gas_score      int32
smartway                 object
dtype: object

In [41]:
v08.dtypes == v18.dtypes

record_year             True
model                   True
displ                   True
cyl                     True
trans                   True
drive                   True
fuel                    True
cert_region             True
veh_class               True
air_pollution_score     True
city_mpg                True
hwy_mpg                 True
cmb_mpg                 True
greenhouse_gas_score    True
smartway                True
dtype: bool

In [42]:
v08.to_csv('./clean_2008.csv')
v18.to_csv('./clean_2018.csv')

In [43]:
clean_df = pd.concat([v08, v18])

In [44]:
clean_df.head(10)

,record_year,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,2008,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,CA,SUV,7.0,15.0,20.0,17.0,4,no
1,2008,ACURA MDX,3.7,6,Auto-S5,4WD,Gasoline,FA,SUV,6.0,15.0,20.0,17.0,4,no
2,2008,ACURA RDX,2.3,4,Auto-S5,4WD,Gasoline,CA,SUV,7.0,17.0,22.0,19.0,5,no
3,2008,ACURA RDX,2.3,4,Auto-S5,4WD,Gasoline,FA,SUV,6.0,17.0,22.0,19.0,5,no
4,2008,ACURA RL,3.5,6,Auto-S5,4WD,Gasoline,CA,midsize car,7.0,16.0,24.0,19.0,5,no
5,2008,ACURA RL,3.5,6,Auto-S5,4WD,Gasoline,FA,midsize car,6.0,16.0,24.0,19.0,5,no
6,2008,ACURA TL,3.2,6,Auto-S5,2WD,Gasoline,CA,midsize car,7.0,18.0,26.0,21.0,6,yes
7,2008,ACURA TL,3.5,6,Auto-S5,2WD,Gasoline,CA,midsize car,7.0,17.0,26.0,20.0,6,yes
8,2008,ACURA TL,3.5,6,Man-6,2WD,Gasoline,CA,midsize car,7.0,18.0,27.0,21.0,6,yes
9,2008,ACURA TL,3.2,6,Auto-S5,2WD,Gasoline,FA,midsize car,6.0,18.0,26.0,21.0,6,no